/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: "#121617",
        "outline-variant": "#c4c6cd",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4fe",
        "on-secondary-fixed-variant": "#004395",
        "tertiary-fixed": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        outline: "#74777d",
        "surface-container-highest": "#d3e4fe",
        "surface": "#f8f9ff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#44474c",
        primary: "#041627",
        "on-primary-container": "#8192a7",
        "surface-container": "#e5eeff",
        "on-secondary-fixed": "#001a42",
        error: "#ba1a1a",
        "primary-fixed-dim": "#b7c8de",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-container": "#272a2c",
        "primary-fixed": "#d2e4fb",
        "on-surface": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#444749",
        secondary: "#0058be",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#38485a",
        "on-primary-fixed": "#0b1d2d",
        "secondary-fixed": "#d8e2ff",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "inverse-surface": "#213145",
        "on-tertiary-container": "#8e9193",
        "primary-container": "#1a2b3c",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#4f6073",
        "surface-container-high": "#dce9ff",
        background: "#f8f9ff",
        "inverse-primary": "#b7c8de",
        "on-secondary-container": "#fefcff",
        "secondary-container": "#2170e4",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        base: "4px",
        lg: "40px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        xl: "64px",
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
